;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;  This file is part of the Codex semantics library.                     ;;
;;                                                                        ;;
;;  Copyright (C) 2013-2025                                               ;;
;;    CEA (Commissariat à l'énergie atomique et aux énergies              ;;
;;         alternatives)                                                  ;;
;;                                                                        ;;
;;  you can redistribute it and/or modify it under the terms of the GNU   ;;
;;  Lesser General Public License as published by the Free Software       ;;
;;  Foundation, version 2.1.                                              ;;
;;                                                                        ;;
;;  It is distributed in the hope that it will be useful,                 ;;
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of        ;;
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ;;
;;  GNU Lesser General Public License for more details.                   ;;
;;                                                                        ;;
;;  See the GNU Lesser General Public License version 2.1                 ;;
;;  for more details (enclosed in the file LICENSE).                      ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(rule
 (with-stdout-to
     binsec_webapp_string.ml
   (progn
     (echo "let binsec_webapp_dot_bc_dot_js = {codexembed|")
     (cat js/binsec_webapp.bc.js)
     (echo "|codexembed}"))))

(rule
 (with-stdout-to
     tailwindcss_string.ml
   (progn
     (echo "let tailwind4_dot_1_dot_5_dot_css = {codexembed|")
     (cat deps/tailwind4.1.5.css)
     (echo "|codexembed}"))))

(rule
 (with-stdout-to
     graphviz_string.ml
   (progn
     (echo "let graphviz_dot_umd_dot_js = {codexembed|")
     (cat deps/graphviz.umd.js)
     (echo "|codexembed}"))))

; (rule
;   (targets d3_string.ml d3_string.mli)
;   (deps deps/d3.v7.min.js)
;   (action
;     (run ocaml-embed-file %{deps} -output d3_string)))

; (rule
;   (targets d3_graphviz_string.ml d3_graphviz_string.mli)
;   (deps deps/d3-graphviz.min.js)
;   (action
;     (run ocaml-embed-file %{deps} -output d3_graphviz_string)))


(rule
 (with-stdout-to
     bundle_string.ml
   (progn
     (echo "let bundle_output_dot_js = {codexembed|")
     (cat deps/js/bundle-output.js)
     (echo "|codexembed}"))))

; (rule
;   (targets clusterizecss_string.ml clusterizecss_string.mli)
;   (deps deps/clusterize.css)
;   (action
;     (run ocaml-embed-file %{deps} -output clusterizecss_string)))

; (rule
;   (targets clusterizeminjs_string.ml clusterizeminjs_string.mli)
;   (deps deps/clusterize.min.js)
;   (action
;     (run ocaml-embed-file %{deps} -output clusterizeminjs_string)))

(library 
  (name interface)
  (public_name codex.gui.interface)
  (libraries codex.syntax_tree codex.binarytrace)
  (modules interface))


(library 
  (name gui)
  (public_name codex.gui)
  (libraries codex.file_to_html unix base64 (re_export codex.gui.interface)
  	     codex.syntax_tree)
  (modules :standard \ interface))

(documentation
  (package codex))
