##########################################################################
#  This file is part of the Codex semantics library.                     #
#                                                                        #
#  Copyright (C) 2013-2025                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file LICENSE).                      #
#                                                                        #
##########################################################################

# Build with:
# $ docker build -f devenv/Dockerfile.alpine -t codex:alpine .

# Run with:
# $ docker run -it --rm --name codex_alpine codex:alpine

# Extract binaries (when the above container is running)
# $ docker cp codex_alpine:/home/ocaml/codex/_build/default/binsec/binsec_codex.exe .

# Start with an alpine linux image with opam in it, for musl
FROM ocamlpro/ocaml:4.14 as first
RUN opam update
RUN opam switch create optstatic --packages=ocaml-variants.4.14.1+options,ocaml-option-static,ocaml-option-flambda,ocaml-option-no-flat-float-array
RUN opam switch optstatic
RUN eval $(opam env)

# Install Codex dependencies.
# C++ and bash is needed for cudd,
# GNU tar is needed for frama-c
# Binsec_codex needs npm
RUN sudo apk add g++ bash tar npm
COPY --chown=ocaml:ocaml ./*.opam /home/ocaml/codex/
RUN opam install ./codex/ --deps-only

# Install Codex
COPY  --chown=ocaml:ocaml . /home/ocaml/codex

RUN cd codex && opam exec -- dune build -p codex
RUN cd codex/frama-c && opam exec -- dune build --profile staticrelease frama_c_codex.exe
RUN cd codex && opam exec -- dune build --profile staticrelease binsec/binsec_codex.exe

#  Local Variables:
#  mode: shell-script
#  End:
