##########################################################################
#  This file is part of the Codex semantics library.                     #
#                                                                        #
#  Copyright (C) 2013-2025                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file LICENSE).                      #
#                                                                        #
##########################################################################

# This dockerfile test the codex installation instruction from the README
# by running them on a blank debian system.

# This should not really be used to build codex docker images, since using an
# opam docker as base is preferrable in that case.

# Build: docker build -f devenv/Dockerfile.bare-install --name codex:install .
# Run: docker run -it --rm --name codex codex:install

FROM debian:latest

RUN apt-get update
RUN apt-get install -y unzip bubblewrap git build-essential # OPAM dependencies
RUN apt-get install -y opam # bash -c "sh <(curl -fsSL https://opam.ocaml.org/install.sh)"
RUN opam init --bare -y

RUN apt-get install -y bc libgmp-dev liblmdb-dev \
        pkg-config autoconf graphviz libexpat1-dev zlib1g-dev libcairo2-dev \
        libexpat1-dev libgtk-3-dev libgtksourceview-3.0-dev libgnomecanvas2-dev \
        cmake time z3 gcc-multilib libev-dev libssl-dev npm curl

RUN opam switch create codex ocaml-base-compiler.4.14.2
RUN eval $(opam env --switch=codex)

COPY . /home/codex
WORKDIR /home/codex

RUN opam install . --deps-only -y
RUN eval $(opam env) && dune build
