(**************************************************************************)
(*  This file is part of the Codex semantics library.                     *)
(*                                                                        *)
(*  Copyright (C) 2013-2025                                               *)
(*    CEA (Commissariat à l'énergie atomique et aux énergies              *)
(*         alternatives)                                                  *)
(*                                                                        *)
(*  you can redistribute it and/or modify it under the terms of the GNU   *)
(*  Lesser General Public License as published by the Free Software       *)
(*  Foundation, version 2.1.                                              *)
(*                                                                        *)
(*  It is distributed in the hope that it will be useful,                 *)
(*  but WITHOUT ANY WARRANTY; without even the implied warranty of        *)
(*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *)
(*  GNU Lesser General Public License for more details.                   *)
(*                                                                        *)
(*  See the GNU Lesser General Public License version 2.1                 *)
(*  for more details (enclosed in the file LICENSE).                      *)
(*                                                                        *)
(**************************************************************************)

(* Frama-C parses some json file that prevent using a standalone binary. Prevent that. *)
(* open Frama_c_kernel;; *)
(* Machine.init_builtins_ref := (fun () -> ());; *)
(* Cil_builtins.init_builtins (); *)

(* Do not load other plugins as the plugin repository may not exist. *)
Kernel.AutoLoadPlugins.set false;;

let () = Frama_c_kernel.Boot.boot ()
(* Implicit exit 0 if we haven't exited yet *)
